Sprint 8 solution time and duration
Valentina-VK/java-kanban pull request #10
Opened 2024-11-29 12:49 UTC by Valentina-VK

Add new functionality: prioritize tasks and check if they overlap in execution time. Write some tests

2024-11-30 13:34 UTC, afomkina requested changes

2024-11-30 13:34 UTC, afomkina commented on .idea/runConfigurations/Main.xml
Нужно удалить папку `idea` из удаленного репозитория

2024-11-30 13:34 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +    Path path;
Нужно вернуть модификаторы `private final`

2024-11-30 13:34 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +        LocalDateTime startTime = LocalDateTime.parse(fieldsOfTask[5], DateTimeFormatter.ofPattern("HH:mm_dd.MM.yyyy"));
Паттер лучше вынести в отдельный файл и сделать глабольной константой, чтобы можно было переиспользовать во всем проекте

2024-11-30 13:34 UTC, afomkina commented on src/manager/InMemoryTaskManager.java
> +import java.util.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/ru/using-wildcard-imports-in-java/#:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D1%85%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2%20%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B5,%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D1%81%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%B0%20%D0%B8%D0%BC%D0%B5%D0%BD.) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2024-11-30 13:34 UTC, afomkina commented on src/manager/InMemoryTaskManager.java
> +    static final LocalDateTime NO_TIME = LocalDateTime.of(1, 1, 1, 0, 0);
У поля должен быть модификатор доступа

2024-11-30 13:34 UTC, afomkina commented on src/manager/InMemoryTaskManager.java
> +        boolean allSubNew = listIdOfSubtasks.stream().map(idSub -> subtaskList.get(idSub).getStatus())
Стримы принято разбивать по строкам для лучшей читаемости:
```suggestion
        boolean allSubNew = listIdOfSubtasks.stream()
            .map(idSub -> subtaskList.get(idSub).getStatus())
            .allMatch(status -> status == Status.NEW);
```
Поправь, пожалуйста, для всех стримов

2024-11-30 13:34 UTC, afomkina commented on test/manager/FileBackedTaskManagerTest.java
В классе `InMemoryHistoryManagerTest`, поля класса не должны быть статическими

2024-11-30 13:34 UTC, afomkina commented on test/manager/InMemoryTaskManagerTest.java
> +public class InMemoryTaskManagerTest extends TaskManagerTest<InMemoryTaskManager> {
Все тесты из данного класса, также применимы и к `FileBackedTaskManager`. Нужно перенести их в `TaskManagerTest`, а отсюда удалить

2024-11-30 13:34 UTC, afomkina commented on test/task/EpicTest.java
У полей класса не хватает модификаторов доступа

2024-11-30 13:34 UTC, afomkina commented on test/task/SubtaskTest.java
У полей класса не хватает модификатора доступа

2024-11-30 13:34 UTC, afomkina commented on test/manager/TaskManagerTest.java
> +        Subtask subtask1 = new Subtask("Test addNewSubTask1", "Test addNewTask description",
Вместо того, чтобы в каждом тесте создавать одинаковые объекты, можно вынести их создание на уровень класса или в метод `@BeforeEach`

2024-11-30 13:51 UTC, Valentina-VK commented on src/manager/FileBackedTaskManager.java
> +    Path path;
ok

2024-11-30 13:51 UTC, Valentina-VK commented on .idea/runConfigurations/Main.xml
ok

2024-11-30 14:02 UTC, Valentina-VK commented on src/manager/InMemoryTaskManager.java
> +import java.util.*;
ok

2024-11-30 14:03 UTC, Valentina-VK commented on src/manager/InMemoryTaskManager.java
> +    static final LocalDateTime NO_TIME = LocalDateTime.of(1, 1, 1, 0, 0);
ok

2024-11-30 14:20 UTC, Valentina-VK commented on src/manager/FileBackedTaskManager.java
> +        LocalDateTime startTime = LocalDateTime.parse(fieldsOfTask[5], DateTimeFormatter.ofPattern("HH:mm_dd.MM.yyyy"));
ok

2024-11-30 14:30 UTC, Valentina-VK commented on src/manager/InMemoryTaskManager.java
> +        boolean allSubNew = listIdOfSubtasks.stream().map(idSub -> subtaskList.get(idSub).getStatus())
ok

2024-11-30 14:37 UTC, Valentina-VK commented on test/manager/FileBackedTaskManagerTest.java
ok

2024-11-30 14:37 UTC, Valentina-VK commented on test/manager/InMemoryTaskManagerTest.java
> +public class InMemoryTaskManagerTest extends TaskManagerTest<InMemoryTaskManager> {
ok

2024-11-30 14:44 UTC, Valentina-VK commented on test/task/SubtaskTest.java
ok

2024-11-30 14:44 UTC, Valentina-VK commented on test/task/EpicTest.java
ok

2024-11-30 15:08 UTC, Valentina-VK commented on test/manager/TaskManagerTest.java
> +        Subtask subtask1 = new Subtask("Test addNewSubTask1", "Test addNewTask description",
ok

2024-12-01 11:29 UTC, afomkina approved these changes

2024-12-01 14:59 UTC, merged