Sprint 9 solution HTTP API
Valentina-VK/java-kanban pull request #11
Opened 2024-12-11 17:51 UTC by Valentina-VK

Implement API in which the endpoints will correspond to calls to the basic methods of the TaskManager

2024-12-12 13:28 UTC, afomkina requested changes

2024-12-12 13:28 UTC, afomkina commented on src/server/BaseHttpHandler.java
> +    public void handle(HttpExchange httpExchange) throws IOException {
Метод не реализован

2024-12-12 13:28 UTC, afomkina commented on src/server/BaseHttpHandler.java
> +        httpExchange.sendResponseHeaders(404, 0);
Задание со `"*"`:
Можно создать отдельное перечисление для HTTP кодов и использовать его вместо "голых" цифр. 
Так код будет выглядеть более читаемо и понятней. 
Примеры можно посмотреть в главе [Конструкторы, поля и методы перечисления](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

2024-12-12 13:28 UTC, afomkina commented on src/server/EpicHandler.java
> +        try {
Нужно поправить во всех хэндлерах:
Лучше использовать [try with resources](https://javarush.com/quests/lectures/questsyntaxpro.level15.lecture00), чтобы не забывать закрывать поток в конце работы

2024-12-12 13:28 UTC, afomkina commented on src/server/EpicHandler.java
> +    EpicHandler(TaskManager manager) {
Нужно поправить во всех хэндлерах:
Лучше сделать констурктор публичным

2024-12-12 13:28 UTC, afomkina commented on src/server/HttpTaskServer.java
> +    public static final int PORT = 8080;
Используется только в данном классе, лучше сделать приватной константой

2024-12-12 13:28 UTC, afomkina commented on test/server/HttpTaskManagerEpicsTest.java
> +    LocalDateTime startTime = LocalDateTime.now();
Нужно поправить во всех тестах:
У всех переменных класса должны быть модификаторы доступа

2024-12-12 13:28 UTC, afomkina commented on test/server/HttpTaskManagerEpicsTest.java
> +        Epic task = new Epic("TestEpic1", "Testing task 1");
Нудно поправить для всех тестов:
Все дублирующие объекты нужно вынести на уровень класса или в метод `@BeforeEach`

2024-12-12 15:21 UTC, Valentina-VK commented on src/server/BaseHttpHandler.java
> +    public void handle(HttpExchange httpExchange) throws IOException {
ok

2024-12-12 15:21 UTC, Valentina-VK commented on src/server/BaseHttpHandler.java
> +        httpExchange.sendResponseHeaders(404, 0);
ok

2024-12-12 15:22 UTC, Valentina-VK commented on src/server/EpicHandler.java
> +        try {
ok

2024-12-12 15:24 UTC, Valentina-VK commented on src/server/EpicHandler.java
> +    EpicHandler(TaskManager manager) {
ok

2024-12-12 15:26 UTC, Valentina-VK commented on src/server/HttpTaskServer.java
> +    public static final int PORT = 8080;
ok

2024-12-12 16:21 UTC, Valentina-VK commented on test/server/HttpTaskManagerEpicsTest.java
> +    LocalDateTime startTime = LocalDateTime.now();
щл

2024-12-12 16:21 UTC, Valentina-VK commented on test/server/HttpTaskManagerEpicsTest.java
> +    LocalDateTime startTime = LocalDateTime.now();
сделано

2024-12-12 16:21 UTC, Valentina-VK commented on test/server/HttpTaskManagerEpicsTest.java
> +        Epic task = new Epic("TestEpic1", "Testing task 1");
ок

2024-12-12 20:17 UTC, afomkina requested changes

2024-12-12 20:17 UTC, afomkina commented on src/server/EpicHandler.java
> +            try {
Нужно поправить для всех хэндлеров:
Должен остаться только один try (httpExchange), try со строки 23 нужно удалить

2024-12-12 20:17 UTC, afomkina commented on src/server/EpicHandler.java
> +        try (httpExchange) {
Код со строк 22-51 повторяется в хэндлерах `SubtaskHandler` (22-51) и `TaskHandler` (22-51), нужно избавиться от дублирований

2024-12-12 20:17 UTC, afomkina commented on src/server/BaseHttpHandler.java
> +        httpExchange.sendResponseHeaders(404, 0);
Здорово, что выполнила дополнительное задание - молодец 👍

2024-12-13 16:00 UTC, Valentina-VK commented on src/server/EpicHandler.java
> +            try {
использовала конструкцию try-catch-finally

2024-12-13 16:00 UTC, Valentina-VK commented on src/server/EpicHandler.java
> +        try (httpExchange) {
Исправлено

2024-12-14 15:00 UTC, afomkina requested changes

2024-12-14 15:00 UTC, afomkina commented on src/server/HttpTaskServer.java
> +        taskManager.addTask(new Task("Task1", "Description of task1"));
Код со строк 53-64 нужно удалить, все задачи теперь создаются через api

2024-12-14 15:00 UTC, afomkina commented on src/server/BaseHttpHandler.java
> +public class BaseHttpHandler implements HttpHandler {
Давай не будем реализовывать в `BaseHttpHandler` интерфес `HttpHandler`, его достаточно иметь в `TaskHandler`, от которого наследуются другие хэндлеры задач

2024-12-14 15:00 UTC, afomkina commented on src/server/TaskHandler.java
> +public class TaskHandler extends BaseHttpHandler {
Здесь давай реализуем интерфейс `HttpHandler`

2024-12-14 15:00 UTC, afomkina commented on src/server/HistoryHandler.java
> +        try {
Код со строк 18-31 повторяется в обработчике `PrioritizedHandler`. Давай создадим абстрактный класс `GenericTypeHandler`,  который будет наследоваться от `BaseHttpHandler` и реализовывать интерфейс `HttpHandler`. В метод `handle` перенесем данный код и создадим абстрактный метод `protected abstract void getByRequest(HttpExchange httpExchange) throws IOException ;`, который мы реализуем в `HistoryHandler` и `PrioritizedHandler`, соответственно эти два хэндлера будут наследовать новый `GenericTypeHandler`. Что поможет нам избежать дублирования кода

2024-12-15 00:43 UTC, Valentina-VK commented on src/server/HttpTaskServer.java
> +        taskManager.addTask(new Task("Task1", "Description of task1"));
сделано

2024-12-15 00:44 UTC, Valentina-VK commented on src/server/BaseHttpHandler.java
> +public class BaseHttpHandler implements HttpHandler {
Выполнила

2024-12-15 00:44 UTC, Valentina-VK commented on src/server/TaskHandler.java
> +public class TaskHandler extends BaseHttpHandler {
ок

2024-12-15 00:44 UTC, Valentina-VK commented on src/server/HistoryHandler.java
> +        try {
Создала новый класс GenericTypeHandler

2024-12-15 15:42 UTC, afomkina approved these changes

2024-12-16 00:01 UTC, merged